  version: '3.8'

  services:
    app:
      build:
        context: ..
        dockerfile: ./docker/Dockerfile
      container_name: nestjs-app
      restart: always
      ports:
        - "3000:3000"
      env_file:
        - ../.env
      volumes:
        - ../:/app
      command: npm run start:dev
      depends_on:
        - mongo
      environment:
        MONGO_URI: mongodb://mongo:27017/nestjs-database

    mongo:
      image: mongo:6
      container_name: mongodb
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db

  volumes:
    mongo-data:
